# Generated by Django 4.0.6 on 2022-07-08 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='shift',
            new_name='age',
        ),
    ]
