# Generated by Django 4.0.6 on 2022-07-08 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_shift_customuser_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='age',
            new_name='shift',
        ),
    ]
