# Generated by Django 4.0.6 on 2022-07-08 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_age_customuser_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='badge',
            field=models.TextField(blank=True, null=True),
        ),
    ]
